top_srcdir   = /root/distr/httpd-2.2.3
top_builddir = /root/distr/httpd-2.2.3
srcdir       = /root/distr/httpd-2.2.3/modules/echo
builddir     = /root/distr/httpd-2.2.3/modules/echo
VPATH        = /root/distr/httpd-2.2.3/modules/echo

include $(top_srcdir)/build/special.mk

