#! /bin/sh

prefix="/usr/local"
exec_prefix="${prefix}"
version="5.1.6"
includedir="${prefix}/include/php"
includes="-I$includedir -I$includedir/main -I$includedir/TSRM -I$includedir/Zend -I$includedir/ext"
ldflags=""
libs="-lcrypt   -lcrypt -lresolv -lm -ldl -lnsl  -lxml2 -lxml2 -lxml2 -lcrypt -lxml2 -lxml2 -lxml2 -lcrypt "
extension_dir='/usr/local/lib/php/extensions/no-debug-non-zts-20050922'
program_prefix=""
program_suffix=""
exe_extension=""
php_binary="${exec_prefix}/bin/${program_prefix}php${program_suffix}${exe_extension}"

case "$1" in
--prefix)
	echo $prefix;;
--includes)
	echo $includes;;
--ldflags)
	echo $ldflags;;
--libs)
	echo $libs;;
--extension-dir)
	echo $extension_dir;;
--include-dir)
	echo $includedir;;
--php-binary)
	echo $php_binary;;
--version)
	echo $version;;
*)
	echo "Usage: $0 [--prefix|--includes|--ldflags|--libs|--extension-dir|--include-dir|--php-binary|--version]"
	exit 1;;
esac

exit 0
