top_srcdir   = /var/www/httpd-2.2.3
top_builddir = /var/www/httpd-2.2.3
srcdir       = /var/www/httpd-2.2.3/modules/cache
builddir     = /var/www/httpd-2.2.3/modules/cache
VPATH        = /var/www/httpd-2.2.3/modules/cache

include $(top_srcdir)/build/special.mk

