top_srcdir   = /root/distr/httpd-2.2.3
top_builddir = /root/distr/httpd-2.2.3
srcdir       = /root/distr/httpd-2.2.3/modules/cache
builddir     = /root/distr/httpd-2.2.3/modules/cache
VPATH        = /root/distr/httpd-2.2.3/modules/cache

include $(top_srcdir)/build/special.mk

