top_srcdir   = /root/distr/httpd-2.2.3
top_builddir = /root/distr/httpd-2.2.3
srcdir       = /root/distr/httpd-2.2.3/modules/aaa
builddir     = /root/distr/httpd-2.2.3/modules/aaa
VPATH        = /root/distr/httpd-2.2.3/modules/aaa

include $(top_srcdir)/build/special.mk

