top_srcdir   = /var/www/httpd-2.2.3
top_builddir = /var/www/httpd-2.2.3
srcdir       = /var/www/httpd-2.2.3/modules/aaa
builddir     = /var/www/httpd-2.2.3/modules/aaa
VPATH        = /var/www/httpd-2.2.3/modules/aaa

include $(top_srcdir)/build/special.mk

