top_srcdir   = /var/www/httpd-2.2.3
top_builddir = /var/www/httpd-2.2.3
srcdir       = /var/www/httpd-2.2.3/modules/http
builddir     = /var/www/httpd-2.2.3/modules/http
VPATH        = /var/www/httpd-2.2.3/modules/http

include $(top_srcdir)/build/special.mk

