top_srcdir   = /root/distr/httpd-2.2.3
top_builddir = /root/distr/httpd-2.2.3
srcdir       = /root/distr/httpd-2.2.3/modules/http
builddir     = /root/distr/httpd-2.2.3/modules/http
VPATH        = /root/distr/httpd-2.2.3/modules/http

include $(top_srcdir)/build/special.mk

