top_srcdir   = /root/distr/httpd-2.2.3
top_builddir = /root/distr/httpd-2.2.3
srcdir       = /root/distr/httpd-2.2.3/modules/filters
builddir     = /root/distr/httpd-2.2.3/modules/filters
VPATH        = /root/distr/httpd-2.2.3/modules/filters

include $(top_srcdir)/build/special.mk

