top_srcdir   = /var/www/httpd-2.2.3
top_builddir = /var/www/httpd-2.2.3
srcdir       = /var/www/httpd-2.2.3/modules/filters
builddir     = /var/www/httpd-2.2.3/modules/filters
VPATH        = /var/www/httpd-2.2.3/modules/filters

include $(top_srcdir)/build/special.mk

