top_srcdir   = /var/www/httpd-2.2.3
top_builddir = /var/www/httpd-2.2.3
srcdir       = /var/www/httpd-2.2.3/os
builddir     = /var/www/httpd-2.2.3/os
VPATH        = /var/www/httpd-2.2.3/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
