top_srcdir   = /root/distr/httpd-2.2.3
top_builddir = /root/distr/httpd-2.2.3
srcdir       = /root/distr/httpd-2.2.3/os
builddir     = /root/distr/httpd-2.2.3/os
VPATH        = /root/distr/httpd-2.2.3/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
