top_srcdir   = /root/distr/httpd-2.2.3
top_builddir = /root/distr/httpd-2.2.3
srcdir       = /root/distr/httpd-2.2.3/server/mpm
builddir     = /root/distr/httpd-2.2.3/server/mpm
VPATH        = /root/distr/httpd-2.2.3/server/mpm

SUBDIRS = $(MPM_SUBDIR_NAME)

include $(top_builddir)/build/rules.mk
