top_srcdir   = /var/www/httpd-2.2.3
top_builddir = /var/www/httpd-2.2.3
srcdir       = /var/www/httpd-2.2.3/server/mpm
builddir     = /var/www/httpd-2.2.3/server/mpm
VPATH        = /var/www/httpd-2.2.3/server/mpm

SUBDIRS = $(MPM_SUBDIR_NAME)

include $(top_builddir)/build/rules.mk
