top_srcdir   = /root/distr/httpd-2.2.3
top_builddir = /root/distr/httpd-2.2.3
srcdir       = /root/distr/httpd-2.2.3/modules/metadata
builddir     = /root/distr/httpd-2.2.3/modules/metadata
VPATH        = /root/distr/httpd-2.2.3/modules/metadata

include $(top_srcdir)/build/special.mk

