top_srcdir   = /var/www/httpd-2.2.3
top_builddir = /var/www/httpd-2.2.3
srcdir       = /var/www/httpd-2.2.3/modules/generators
builddir     = /var/www/httpd-2.2.3/modules/generators
VPATH        = /var/www/httpd-2.2.3/modules/generators

include $(top_srcdir)/build/special.mk

