top_srcdir   = /root/distr/httpd-2.2.3
top_builddir = /root/distr/httpd-2.2.3
srcdir       = /root/distr/httpd-2.2.3/modules/generators
builddir     = /root/distr/httpd-2.2.3/modules/generators
VPATH        = /root/distr/httpd-2.2.3/modules/generators

include $(top_srcdir)/build/special.mk

