top_srcdir   = /var/www/httpd-2.2.3
top_builddir = /var/www/httpd-2.2.3
srcdir       = /var/www/httpd-2.2.3/srclib
builddir     = /var/www/httpd-2.2.3/srclib
VPATH        = /var/www/httpd-2.2.3/srclib

BUILD_SUBDIRS = $(AP_BUILD_SRCLIB_DIRS)
CLEAN_SUBDIRS = $(AP_CLEAN_SRCLIB_DIRS)

include $(top_builddir)/build/rules.mk
