top_srcdir   = /root/distr/httpd-2.2.3
top_builddir = /root/distr/httpd-2.2.3
srcdir       = /root/distr/httpd-2.2.3/modules/loggers
builddir     = /root/distr/httpd-2.2.3/modules/loggers
VPATH        = /root/distr/httpd-2.2.3/modules/loggers

include $(top_srcdir)/build/special.mk

