top_srcdir   = /var/www/httpd-2.2.3
top_builddir = /var/www/httpd-2.2.3
srcdir       = /var/www/httpd-2.2.3/modules/loggers
builddir     = /var/www/httpd-2.2.3/modules/loggers
VPATH        = /var/www/httpd-2.2.3/modules/loggers

include $(top_srcdir)/build/special.mk

