top_srcdir   = /root/distr/httpd-2.2.3
top_builddir = /root/distr/httpd-2.2.3
srcdir       = /root/distr/httpd-2.2.3/server/mpm/prefork
builddir     = /root/distr/httpd-2.2.3/server/mpm/prefork
VPATH        = /root/distr/httpd-2.2.3/server/mpm/prefork

LTLIBRARY_NAME    = libprefork.la
LTLIBRARY_SOURCES = prefork.c

include $(top_srcdir)/build/ltlib.mk
