top_srcdir   = /var/www/httpd-2.2.3
top_builddir = /var/www/httpd-2.2.3
srcdir       = /var/www/httpd-2.2.3/server/mpm/prefork
builddir     = /var/www/httpd-2.2.3/server/mpm/prefork
VPATH        = /var/www/httpd-2.2.3/server/mpm/prefork

LTLIBRARY_NAME    = libprefork.la
LTLIBRARY_SOURCES = prefork.c

include $(top_srcdir)/build/ltlib.mk
