top_srcdir   = /root/distr/httpd-2.2.3
top_builddir = /root/distr/httpd-2.2.3
srcdir       = /root/distr/httpd-2.2.3/modules/mappers
builddir     = /root/distr/httpd-2.2.3/modules/mappers
VPATH        = /root/distr/httpd-2.2.3/modules/mappers

include $(top_srcdir)/build/special.mk

