top_srcdir   = /var/www/httpd-2.2.3
top_builddir = /var/www/httpd-2.2.3
srcdir       = /var/www/httpd-2.2.3/modules/mappers
builddir     = /var/www/httpd-2.2.3/modules/mappers
VPATH        = /var/www/httpd-2.2.3/modules/mappers

include $(top_srcdir)/build/special.mk

