top_srcdir   = /root/distr/httpd-2.2.3
top_builddir = /root/distr/httpd-2.2.3
srcdir       = /root/distr/httpd-2.2.3/modules
builddir     = /root/distr/httpd-2.2.3/modules
VPATH        = /root/distr/httpd-2.2.3/modules

SUBDIRS = $(MODULE_DIRS)
CLEAN_SUBDIRS = $(MODULE_CLEANDIRS)

include $(top_builddir)/build/rules.mk

