top_srcdir   = /var/www/httpd-2.2.3
top_builddir = /var/www/httpd-2.2.3
srcdir       = /var/www/httpd-2.2.3/modules
builddir     = /var/www/httpd-2.2.3/modules
VPATH        = /var/www/httpd-2.2.3/modules

SUBDIRS = $(MODULE_DIRS)
CLEAN_SUBDIRS = $(MODULE_CLEANDIRS)

include $(top_builddir)/build/rules.mk

